strat-dat:
  build: "."
  mem_limit: 128m
  restart: always
  container_name: strat-dat
  volumes:
    - .:/home/app/strat-dat
    - /home/app/strat-dat/local
  ports:
    - 8080
  environment:
    PERL_ENV: production
  labels:
    SERVICE_80_NAME: strat-dat
    SERVICE_80_CHECK_HTTP: /
    SERVICE_80_CHECK_INTERVAL: 5s
    SERVICE_443_IGNORE: 'yes'
    SERVICE_TAGS: production
